apiVersion: v1
clusters:
- cluster:
    server: YOUR_CLUSTER_ENDPOINT_HERE
    certificate-authority-data: YOUR_CA_CERTIFICATE_HERE
  name: my-eks-cluster
contexts:
- context:
    cluster: my-eks-cluster
    user: aws-user
  name: my-eks-cluster
current-context: my-eks-cluster
kind: Config
preferences: {}
users:
- name: aws-user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws
      args:
      - eks
      - get-token
      - --cluster-name
      - my-eks-cluster
      - --region
      - us-east-1